# Generated by Django 4.1.5 on 2023-01-22 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30, verbose_name='Полное имя')),
                ('chat_id', models.CharField(max_length=10, verbose_name='ID TG CHAT')),
            ],
            options={
                'verbose_name': 'Курьер',
                'verbose_name_plural': 'Курьеры',
            },
        ),
        migrations.CreateModel(
            name='Florist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30, verbose_name='Полное имя')),
                ('chat_id', models.CharField(max_length=30, verbose_name='ID TG CHAT')),
            ],
            options={
                'verbose_name': 'Флорист',
                'verbose_name_plural': 'Флористы',
            },
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название букета')),
                ('description', models.TextField(max_length=100, verbose_name='Описание букета')),
                ('type', models.CharField(max_length=30, verbose_name='Тип цветов')),
                ('image', models.ImageField(upload_to='', verbose_name='Ссылка на фото')),
                ('category', models.CharField(max_length=30, verbose_name='Категория букета')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена букета')),
                ('florist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='florists', to='bot.florist', verbose_name='Флорист')),
            ],
            options={
                'verbose_name': 'Букет',
                'verbose_name_plural': 'Букеты',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Полное имя')),
                ('chat_id', models.CharField(max_length=10, verbose_name='ID TG CHAT')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Баланс пользователя')),
                ('access', models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных')),
                ('admin', models.BooleanField(default=False, verbose_name='Администратор')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=30, verbose_name='Адрес покупателя')),
                ('delivery_date', models.DateTimeField(verbose_name='Дата доставки')),
                ('count', models.IntegerField(default=1, verbose_name='Кол-во букетов')),
                ('courier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couriers', to='bot.courier', verbose_name='Курьер')),
                ('flower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_flowers', to='bot.flower', verbose_name='Букет')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_orders', to='bot.user', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
