# Generated by Django 4.1.5 on 2023-01-18 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='florist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='florists', to='bot.florist', verbose_name='Флорист'),
        ),
        migrations.AlterField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couriers', to='bot.courier', verbose_name='Курьер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='flower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_flowers', to='bot.flower', verbose_name='Букет'),
        ),
    ]
