# Generated by Django 4.1.5 on 2023-01-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_flower_florist_alter_order_courier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='chat_id',
            field=models.CharField(max_length=10, verbose_name='ID TG CHAT'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена букета'),
        ),
        migrations.AlterField(
            model_name='order',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Кол-во букетов'),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Баланс пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='chat_id',
            field=models.CharField(max_length=10, verbose_name='ID TG CHAT'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=12, verbose_name='Номер телефона'),
        ),
    ]
